### ISSUE TITLE
Bin Folder path is hard-coded

### ISSUE THREAD

**Issue by fschneidereit** [johnmcbride/OpenBinFolder-VSExtension#1]
In essence:

`Path.Combine(_projectPath, "bin");`

This is problematic because it makes the assumption that the bin folder is always a directory named "bin" under the project path, which is not true because it can be customized; therefore, the extension will not work correctly for projects that defined an output path that is different than "/bin".

I think the best way to fix this would be to get the output path directly from the project file. I don't know whether this is possible via DTE; if it's not, you could use the MSBuild engine/framework to parse the project file and read the OutputPath property of the current configuration (which feels like a hack since this information should be present in the IDE somewhere).

**Comment by johnmcbride** [comment]
Thanks - This is true that the assumption is bin directory is the default. We might be able to get the output directory via automation but will have to look at it.

**Comment by lukasf** [comment]
Do you intend to publish a new version of the extension at some point? The latest version is still V1.0 from beginning 2016, and it does not contain this pretty improtant bugfix.
